# Generated by Django 4.2.16 on 2024-11-30 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('admissao', models.DateField(default=django.utils.timezone.now)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='JoinAPIApp.cargo')),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
    ]
