# Generated by Django 4.2.16 on 2024-11-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JoinAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id_cargo',
            field=models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='JoinAPIApp.cargo'),
        ),
    ]
