# Generated by Django 4.2.16 on 2024-11-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoinAPIApp', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='dataDeExpiracao',
            new_name='data_de_expiracao',
        ),
    ]
