# Generated by Django 4.2.16 on 2024-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoinAPIApp', '0004_rename_datadeexpiracao_location_data_de_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data_de_expiracao',
            field=models.DateField(),
        ),
    ]
